name: Generate contribution graph

on:
  schedule:
    - cron: "0 0 * * FRI" 
  workflow_dispatch:

jobs:
  Generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}
      - name: Gen contributions graph snake in format GIF
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
      - name: Save
        uses: mikeal/publish-to-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH_NAME: 'master'
